Prices for biomes
IridiumLLC/IridiumSkyblock pull request #321
Opened 2020-10-23 22:26 UTC by MertUnverdi

2020-10-23 22:45 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/gui/BiomeGUI.java
>                      setItem(slot, Utils.makeItem(IridiumSkyblock.getInventories().biome, Collections.singletonList(new Utils.Placeholder("biome", WordUtils.capitalize(biome.name().toLowerCase().repla
I think that you should be able to display the cost in the GUI. Add a placeholder here

2020-10-23 22:47 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/gui/BiomeGUI.java
> +import com.iridium.iridiumskyblock.*;
Wildcard imports are bad

2020-10-23 22:50 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/gui/BiomeGUI.java
> +    public void sendMessage(String biome) {
Maybe change it to a better name like `sendBiomeChangeMessage()` :)

2020-10-23 23:28 UTC, IridiumLLC requested changes

2020-10-23 23:28 UTC, IridiumLLC commented on src/main/java/com/iridium/iridiumskyblock/gui/BiomeGUI.java
> +        for (XBiome biome : IridiumSkyblock.getConfiguration().islandBiomes.keySet()) {
Can we put
```IridiumSkyblock.getConfiguration().islandBiomes.keySet()```
as a variable here and then sort it alphabetically?

2020-10-23 23:28 UTC, IridiumLLC commented on src/main/java/com/iridium/iridiumskyblock/gui/BiomeGUI.java
> +                        p.sendMessage(Utils.color(IridiumSkyblock.getMessages().biomePurchased
Can we send the message to all members on the island instead of just the person who changed it?

2020-10-24 10:41 UTC, IridiumLLC approved these changes

2020-10-24 10:41 UTC, merged