keepInventory setting for voidTeleport
IridiumLLC/IridiumSkyblock pull request #331
Opened 2020-10-28 16:20 UTC by MertUnverdi

2020-10-28 19:10 UTC, IridiumLLC requested changes

2020-10-28 19:10 UTC, IridiumLLC commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
> +                            player.getInventory().clear();
This wont clear their armor... I think

2020-10-28 19:10 UTC, IridiumLLC commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
> +                        if (!config.keepInventoryOnVoid && (island == user.getIsland() || island.getCoop().contains(user.getIsland().getId())))
Does it matter if they arnt on their island though? If they fall into the void on any island shouldnt they lose their items?

2020-10-28 19:10 UTC, IridiumLLC commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
> +                        if (!config.keepInventoryOnVoid && (island == user.getIsland() || island.getCoop().contains(user.getIsland().getId())))
Why are we doing this code twice in both the if and the else? we should move it outside the statement instead.

(Unless im blind and they are different)

2020-10-28 19:15 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
> +                            player.getInventory().clear();
This suggested by CW_UK and i ask to him for about armors he said  should be delete armors tho

2020-10-29 09:13 UTC, IridiumLLC commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
> +                            player.getInventory().clear();
Sorry, your misunderstanding me. I also think it should clear their armor.

But I think player.getInventory().clear() only clears their inventory, not their armor (I may be wrong)

2020-10-29 09:18 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
> +                            player.getInventory().clear();
Sorry for my bad :(
Also player.getInventory().clear for all
And player.getInventory().getContents() for envanter slots

2020-10-29 09:21 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
> +                            player.getInventory().clear();
i'll change to back when i at home thanks for comments <3

2020-11-01 17:48 UTC, closed without merging