Add options to disable natural mob and/or animal spawns
IridiumLLC/IridiumSkyblock pull request #435
Opened 2020-12-05 21:29 UTC by CW-UK

Adds two config options to control hostile and/or passive natural spawns in Iridium worlds:
- disableNaturalMobSpawns (boolean, default false)
- disableNaturalAnimalSpawns (boolean, default false)

2020-12-06 09:18 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/listeners/CreatureSpawnListener.java
> +            if (!IridiumSkyblock.getIslandManager().isIslandWorld(location) || event.getSpawnReason() != CreatureSpawnEvent.SpawnReason.NATURAL || (!config.disableNaturalAnimalSpawns && !config.disab
Put config option checking to first|second line
`if (!config.disableNaturalMonsterSpawns || !config.disableNaturalAnimalSpawns) return;`
And dont get island just use `IridiumSkyblock.getIslandManager().isIslandWorld(location)`

2020-12-06 13:13 UTC, PeachesMLG requested changes

2020-12-06 13:13 UTC, PeachesMLG commented on src/main/java/com/iridium/iridiumskyblock/configs/Config.java
> +    public boolean disableNaturalMonsterSpawns = false;
would it be better to have an entityBlackList instead? ik some people just want to disable phantoms for example

2020-12-06 14:37 UTC, CW-UK commented on src/main/java/com/iridium/iridiumskyblock/configs/Config.java
> +    public boolean disableNaturalMonsterSpawns = false;
Hmm, that could work. A list for animals and monsters, or just one list combined for all entities? Could also accept an "all" option to prevent anything from spawning naturally, which several other plugins seem to use.

2020-12-07 13:49 UTC, CW-UK commented on src/main/java/com/iridium/iridiumskyblock/configs/Config.java
> +    public boolean disableNaturalMonsterSpawns = false;
Revision below. Using a list seemed a good idea in hindsight, as I myself block natural phantoms and slimes on my servers. I also added a whitelist toggle so you can deny anything except what's listed. That way if you only want (e.g.) sheep to spawn, you don't have to add the remaining 30+ mobs to the list.

I used the name denyNaturalSpawn as I wondered if 'entityBlacklist' would be too similar to 'blockedEntities' or cause confusion with two entity references? Can be changed if you wanted.

2020-12-07 15:47 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/listeners/CreatureSpawnListener.java
>                  return;
unused return :P

2020-12-17 14:54 UTC, PeachesMLG commented on src/main/java/com/iridium/iridiumskyblock/listeners/CreatureSpawnListener.java
> +            if ((!config.denyNaturalSpawnWhitelist && config.denyNaturalSpawn.contains(entity.getType()))
This can be changed to
config.denyNaturalSpawnWhitelist != config.denyNaturalSpawn.contains(entity.getType())
just to make stuff shorter, ill make these changes though

2020-12-17 14:54 UTC, merged