new API LeaderChangeEvent
IridiumLLC/IridiumSkyblock pull request #537
Opened 2021-01-23 20:56 UTC by MertUnverdi

our api is not rich, we could add more events :+1:

2021-01-23 22:38 UTC, dlsf requested changes
In my opinion the event should either be triggered after the confirmation or be changed to something like PreLeaderChangeEvent

2021-01-23 22:49 UTC, dlsf commented
I don't know if this is a useful event tho, I guess we have to wait for @PeachesMLG. An event triggered when the leader actually changes would probably be more useful.

2021-01-23 22:51 UTC, dlsf commented
Also, this event should be triggered by the MembersCommand and MembersGUI

2021-01-23 23:01 UTC, PeachesMLG commented
I dont see why this is needed tbh, why not have it after the confirmation gui?

2021-01-23 23:15 UTC, MertUnverdi commented
cause someone wants ignoring leader change

2021-01-23 23:16 UTC, dlsf commented
But he can still do that when the event gets triggered after the confirmation before the leader actually changes

2021-01-24 18:43 UTC, MertUnverdi commented
nope if event is not cancelled
event will work after then transfer finished
is wrong??
im still thinking is should be before then event cause someones can be wants cancel transfer without permission or anything
ik this plugin doesn't supports p2w but this not counts tho :D

2021-01-24 18:44 UTC, MertUnverdi commented
but if u say change it to before, i can np <3

2021-01-24 19:26 UTC, dlsf approved these changes

2021-01-24 19:27 UTC, dlsf requested changes

2021-01-24 19:27 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/api/PreLeaderChangeEvent.java
> +public class PreLeaderChangeEvent extends IslandEvent implements Cancellable {
Rename the event again

2021-01-24 19:27 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/commands/TransferCommand.java
> +import com.iridium.iridiumskyblock.api.PreLeaderChangeEvent;
Remove this import

2021-01-24 20:09 UTC, merged